os: Windows Server 2012

clone_folder: c:\projects\anima-render

configuration:
  - Debug
  - Release

install:
  cmd: nuget restore

build:
  project: AnimaRender.sln

test: off

artifacts:
  - path: \bin\Debug
    name: AnimaRender-latest-Debug-x86
  - path: \bin\Release
    name: AnimaRender-latest-Release-x86